name: Source Distribution
inputs:
  ghc:
    description: GHC Version
    required: false
    default: latest

runs:
  using: "composite"
  steps:
    - name: Setup Haskell
      uses: haskell-actions/setup@v2.9.0
      with:
        ghc-version: ${{ inputs.ghc }}
        enable-stack: true

    - name: Cache Stack
      uses: actions/cache@v5
      with:
        path: ~/.stack
        key: ${{ runner.os  }}-${{ inputs.ghc }}-stack-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.ghc }}-stack
