name: hmm
version: 0.5.0
github: nalchevanidze/hmm
license: MIT
author: Daviti Nalchevanidze
category: web
synopsis: Haskell Monorepo Manager
maintainer: d.nalchevanidze@gmail.com
copyright: (c) 2019 Daviti Nalchevanidze
license-file: LICENSE
description: CLI tool to manage Haskell monorepos with multi-GHC support
dependencies:
- Glob                  >=  0.7.0     &&  <   1.0.0
- aeson                 >=  1.4.4     &&  <   3.0.0
- base                  >=  4.7.0     &&  <   5.0.0
- base16-bytestring     >=  1.0.0     &&  <   2.0.0
- bytestring            >=  0.10.4    &&  <   0.15.0
- containers            >=  0.4.2.1   &&  <=  0.8
- cryptohash-sha256     >=  0.11.100  &&  <   0.12.0
- directory             >=  1.0       &&  <   2.0
- filepath              >=  1.1.0     &&  <=  1.5.5.0
- modern-uri            >=  0.1.0.0   &&  <   1.0.0
- ormolu                >=  0.5.0     &&  <   1.0.0
- process               >=  1.0.0     &&  <   2.0.0
- relude                >=  0.3.0     &&  <   2.0.0
- req                   >=  3.0.0     &&  <   4.0.0
- text                  >=  1.2.3     &&  <   3.0.0
- unordered-containers  >=  0.2.8     &&  <   0.3.0
- yaml                  >=  0.8.32    &&  <   1.0.0
executables:
  hmm:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
    dependencies:
    - filepath              >=  1.1.0   &&  <=  1.5.5.0
    - optparse-applicative  >=  0.12.0  &&  <   0.20.0
